# Generated by Django 4.1 on 2022-09-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_friendship"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="誕生日"),
        ),
        migrations.AddField(
            model_name="user",
            name="self_introduction",
            field=models.TextField(
                blank=True,
                default="未設定",
                max_length=160,
                null=True,
                verbose_name="自己紹介",
            ),
        ),
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.UniqueConstraint(
                fields=("followee", "follower"), name="unique_friendship"
            ),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
